### ISSUE TITLE
【bug？】过长选区生成切片异常

### ISSUE THREAD

**Issue by Greenleaf2001** [Xinrea/bili-shadowreplay#25]
版本：v1.2.0

使用场景与操作：
已经直播完的正常直播，查看历史记录→编辑切片→选择某一个入点与某一个出点→从选区生成新切片
（选区长度＞20min，典型的一种情况是试图直接选择直播开头和直播结尾尝试生成正常直播录播）
（引起该情况的最短切片长度未测试）
（选区中存在从未播放浏览过的片段）
（补充：即使使用倍速播放完整播放了长选区内全部视频片段，再点击生成新切片，表现为相同的疑似bug表现）
![image](https://github.com/user-attachments/assets/0316d3b6-effb-45ad-afba-5283df69780b)

疑似bug表现：
从选区生成新切片卡住，表现为持续转圈等待，后台直播缓存所在盘（数据盘，无系统读写干扰）无明显IO活动及读写行为。

可能是因为切片的相关功能主要服务于高能时刻的短切片，所以面对长分段片段在文件处理和生成上可能不是强项？也暂时无法取代传统录播姬用于长视频工作流/录播功能/粗切的工作流前置？

**Comment by Xinrea** [comment]
程序安装目录下会有 `bsr.log` 日志文件，可以附上便于分析问题。看起来应该是切片生成失败了，具体原因得看日志，正常来说切片生成都很快，就算一个小时的区间也在十秒以内。

**Comment by Xinrea** [comment]
经过检查是片段数过多导致参数长度超过限制，将会改变切片的生成方式来解决这个问题。

**Comment by Greenleaf2001** [comment]
> 程序安装目录下会有 `bsr.log` 日志文件，可以附上便于分析问题。看起来应该是切片生成失败了，具体原因得看日志，正常来说切片生成都很快，就算一个小时的区间也在十秒以内。

好的，感谢告知日志位置，之后使用的时候如果遇见bug会附上日志
