### ISSUE TITLE
刷新一次页面后界面空白

### ISSUE THREAD

**Issue by RAINighty** [Xinrea/bili-shadowreplay#4]
在程序内右键点了次刷新程序就全空白了，但是看文件还在录制，卸载重装也不管用
![cdc61aa60f14418fb1399f97f65c6fa3](https://github.com/user-attachments/assets/f721a110-d0ca-4930-917c-1adc3038f250)

顺便一提配置文件在哪？卸载重制仍然读取之前配置

**Comment by RAINighty** [comment]
使用geek彻底卸载后可以正常使用

**Comment by Xinrea** [comment]
配置文件位置在：`C:\Users\{user}\AppData\Roaming\bili-shadowreplay\`
目前该项目正在重构中，旧版本暂不维护
